version: '3'

services:

  dash_app:
    restart: always
    build: ./dash
    ports:
      - 8000:8000
    command: gunicorn --bind 0.0.0.0:8000 app:server 
    deploy:
      replicas: 1


  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - dash_app
 
    

