version: '3'

services:

  dash_app:
    restart: always
    build: ./dash
    expose:
      - "8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 app:server 
    deploy:
      replicas: 1


  nginx:
    restart: always
    build: ./nginx
    port:
      - "80:80"
    depends_on:
      - dash_app
    deploy:
      replicas: 1
    

